// <auto-generated />
using System;
using Biblioteca.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001183445_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Biblioteca.Api.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataNascimento = new DateOnly(1839, 6, 21),
                            Nacionalidade = "Brasileira",
                            Nome = "Machado de Assis"
                        },
                        new
                        {
                            Id = 2,
                            DataNascimento = new DateOnly(1920, 12, 10),
                            Nacionalidade = "Brasileira",
                            Nome = "Clarice Lispector"
                        });
                });

            modelBuilder.Entity("Biblioteca.Api.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.ToTable("Livros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoPublicacao = 1899,
                            AutorId = 1,
                            Genero = "Romance",
                            Isbn = "978-85-0000-001-1",
                            Titulo = "Dom Casmurro"
                        },
                        new
                        {
                            Id = 2,
                            AnoPublicacao = 1881,
                            AutorId = 1,
                            Genero = "Romance",
                            Isbn = "978-85-0000-002-8",
                            Titulo = "Memórias Póstumas de Brás Cubas"
                        },
                        new
                        {
                            Id = 3,
                            AnoPublicacao = 1977,
                            AutorId = 2,
                            Genero = "Romance",
                            Isbn = "978-85-0000-003-5",
                            Titulo = "A Hora da Estrela"
                        });
                });

            modelBuilder.Entity("Biblioteca.Api.Models.Livro", b =>
                {
                    b.HasOne("Biblioteca.Api.Models.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Biblioteca.Api.Models.Autor", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
